import { ClerkProvider } from "@clerk/nextjs";

import ReactQueryProvider from "@/providers/react-query";

import "./globals.css";

import { Inter as FontSans } from "next/font/google";

import { NewAccountSheet } from "@/features/accounts/components/NewAccountSheet";
import { cn } from "@/lib/utils";
import { Toaster } from "@components/ui/sonner";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
          <ReactQueryProvider>
            <NewAccountSheet />
            {children}
          </ReactQueryProvider>

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
